"""Registry of every emulator wrapped by (or noted for) this server.

Single source of truth for parameter ranges, unit conventions, citations, and
availability status. The list_emulators / describe_emulator tools serialize
entries from here; tool modules import ranges from here rather than
duplicating them.

status values:
- "active"    : wrapped by a tool in this server, smoke-tested
- "deferred"  : installed in the environment but not yet exposed as a tool
                (typically because first use downloads large model files)
- "planned"   : selected in the catalog but not yet installed/wrapped
"""

EMULATORS: dict[str, dict] = {
    # ------------------------------------------------------------- pk family
    "camb": {
        "family": "pk",
        "role": "reference Boltzmann code: linear P(k) + HMcode-2020 nonlinear",
        "tools": ["compute_linear_pk", "compute_nonlinear_pk"],
        "outputs": "P(k) [(Mpc/h)^3], k [h/Mpc]; any k, any z",
        "ranges": {"note": "solver, not an emulator - any physical parameters"},
        "speed": "~1 s per call",
        "citation": "Lewis & Challinor, https://camb.info",
        "license": "modified LGPL",
        "status": "active",
    },
    "syren": {
        "family": "pk",
        "role": "symbolic (closed-form) linear P(k) + syren-halofit nonlinear",
        "tools": ["compute_linear_pk", "compute_nonlinear_pk"],
        "outputs": "P(k) [(Mpc/h)^3]; k ~ 9e-3..9 h/Mpc, z <~ 3",
        "ranges": {"sigma8": [0.6, 1.0], "Om": [0.2, 0.45], "Ob": [0.03, 0.07],
                   "h": [0.55, 0.85], "ns": [0.85, 1.05]},
        "accuracy": "~0.2% linear, ~1% nonlinear vs EuclidEmulator2",
        "speed": "microseconds; zero data files",
        "citation": "Bartlett et al. arXiv:2311.15865, 2402.17492",
        "license": "MIT",
        "status": "active",
    },
    "baccoemu": {
        "family": "pk",
        "role": "NN linear P(k) + nonlinear boost + baryonification boost",
        "tools": ["compute_linear_pk", "compute_nonlinear_pk",
                  "compute_baryon_suppression", "baryonify_pk"],
        "outputs": "linear k 1e-4..50, boost k 0.01..5 h/Mpc; z <= 3 (boost z <= 1.5)",
        "ranges": {"omega_cold": [0.23, 0.40], "sigma8_cold": [0.73, 0.90],
                   "omega_baryon": [0.04, 0.06], "ns": [0.92, 1.01],
                   "hubble": [0.6, 0.8], "neutrino_mass_eV": [0.0, 0.4],
                   "w0": [-1.15, -0.85], "wa": [-0.3, 0.3]},
        "unit_trap": "parameterized by sigma8_cold / omega_cold (CDM+baryons, not total matter)",
        "accuracy": "~1-2% for k < 5 h/Mpc, z < 1.5",
        "citation": "Angulo et al. arXiv:2004.06245; Arico et al. arXiv:2011.15018",
        "license": "MIT",
        "status": "active",
    },
    "euclidemu2": {
        "family": "pk",
        "role": "nonlinear boost B(k,z) = P_nl/P_lin for nu-w0waCDM",
        "tools": ["compute_nonlinear_pk"],
        "outputs": "boost on k 8.7e-3..9.4 h/Mpc grid, z 0..10 (validated z<=3)",
        "ranges": {"Omm": [0.24, 0.40], "Omb": [0.04, 0.06], "h": [0.61, 0.73],
                   "ns": [0.92, 1.00], "As": [1.7e-9, 2.5e-9],
                   "w0": [-1.3, -0.7], "wa": [-0.7, 0.5], "mnu_eV": [0.0, 0.15]},
        "accuracy": "~1% to k = 10 h/Mpc, z <= 3",
        "citation": "Euclid Collaboration (Knabenhans et al.) arXiv:2010.11288",
        "license": "GPL-3.0",
        "status": "active",
    },
    "csst": {
        "family": "pk",
        "role": "GP emulator: nonlinear P(k) from the Kun suite (CSST)",
        "tools": ["compute_nonlinear_pk"],
        "outputs": "P(k) k 0.00628..10 h/Mpc, z 0..3",
        "ranges": {"Omegab": [0.04, 0.06], "Omegac+b": [0.24, 0.40],
                   "H0": [60, 80], "ns": [0.92, 1.00], "As": [1.7e-9, 2.5e-9],
                   "w0": [-1.3, -0.7], "wa": [-0.5, 0.5], "mnu_eV": [0.0, 0.3]},
        "accuracy": "1% to k = 10 h/Mpc, z <= 2",
        "citation": "Chen et al. arXiv:2502.11160",
        "license": "MIT",
        "note": "vendored numpy-2 patch in external/csstemu (GP predict scalar assignment)",
        "status": "active",
    },
    "gokunemu": {
        "family": "pk",
        "role": "NN nonlinear P(k), 10-parameter space (w0waCDM + Neff + running + mnu)",
        "tools": ["compute_nonlinear_pk"],
        "outputs": "P(k) k 0.006..10 h/Mpc, z 0..3",
        "ranges": {"Om": [0.22, 0.40], "Ob": [0.04, 0.055], "h": [0.60, 0.76],
                   "As": [1.0e-9, 3.0e-9], "ns": [0.80, 1.10],
                   "w0": [-1.30, 0.25], "wa": [-3.0, 0.5],
                   "mnu_eV": [0.0, 0.6], "Neff": [2.2, 4.5],
                   "alpha_s": [-0.05, 0.05],
                   "source": "input_limits-W.txt shipped in the gokunemu package; "
                             "enforced server-side via in_training_box"},
        "accuracy": "~0.5% average",
        "citation": "Yang, Bird, Ho arXiv:2507.07177 (GokuNEmu)",
        "license": "MIT",
        "status": "active",
    },
    # -------------------------------------------------------- gravity family
    "emantis": {
        "family": "gravity",
        "role": "f(R) (Hu-Sawicki) boost B(k) = P_f(R)/P_LCDM, GP emulator",
        "tools": ["compute_mg_boost", "compute_mg_pk"],
        "outputs": "boost, k 0.03..7 h/Mpc, z 0..2",
        "ranges": {"minus_log10_fR0": [4.0, 7.0], "Om": [0.2365, 0.3941],
                   "sigma8_lcdm": [0.6, 1.0]},
        "accuracy": "mostly <1%, max ~3%",
        "citation": "Saez-Casares et al. arXiv:2303.08899",
        "license": "GPL-3.0-or-later",
        "status": "active",
    },
    "ndgpemu": {
        "family": "gravity",
        "role": "nDGP boost, sklearn MLP trained on COLA sims",
        "tools": ["compute_mg_boost", "compute_mg_pk"],
        "outputs": "boost, k <= 5 h/Mpc, z 0..2",
        "ranges": {"H0rc": [0.2, 20.0], "Om": [0.28, 0.36], "Ob": [0.04, 0.06],
                   "ns": [0.92, 1.0], "As": [1.7e-9, 2.5e-9], "h": [0.61, 0.73]},
        "accuracy": "~3% vs MG-AREPO",
        "citation": "Fiorini et al. arXiv:2310.05786",
        "license": "GPL-3.0",
        "status": "active",
    },
    "cubic_galileon": {
        "family": "gravity",
        "role": "cubic Galileon boost, SEPIA GP emulator (author: N. Ramachandra)",
        "tools": ["compute_mg_boost", "compute_mg_pk"],
        "outputs": "boost with GP uncertainty, k 0.02..12 h/Mpc, 51 snapshots z 0..49",
        "ranges": {"Om": [0.275, 0.331], "ns": [0.85, 1.1],
                   "As_1e9": [1.453, 3.291], "h": [0.61, 0.73],
                   "f_phi": [0.02, 1.0]},
        "citation": "github.com/nesar/CubicGalileonEmu (paper in prep)",
        "license": "Apache-2.0",
        "note": "runs on modern scipy via patched SEPIA in external/SEPIA "
                "(sym_pos -> assume_a='pos')",
        "status": "active",
    },
    # ------------------------------------------------------------ cmb family
    "cosmopower_jax": {
        "family": "cmb",
        "role": "NN CMB TT/TE/EE + P(k) emulators (CosmoPower weights, JAX runtime)",
        "tools": ["compute_cmb_cls"],
        "outputs": "raw dimensionless Cl, l = 2..2508; server converts to Dl [muK^2]",
        "ranges": {"params": ["omega_b", "omega_cdm", "h", "tau_reio", "ns",
                              "ln10^10 As"], "note": "Planck-prior-sized box"},
        "citation": "Spurio Mancini et al. arXiv:2106.03846; Piras & Spurio Mancini arXiv:2305.06347",
        "license": "GPL-3.0 + non-commercial rider",
        "status": "active",
    },
    "capse": {
        "family": "cmb",
        "role": "Capse.jl CMB emulator via jaxcapse; CAMB high-precision training",
        "tools": ["compute_cmb_cls"],
        "outputs": "Dl [muK^2] directly, l = 2..5000 (TT/TE/EE/PP)",
        "ranges": {"params": ["ln10^10 As", "ns", "H0", "omega_b", "omega_cdm",
                              "tau"], "note": "parameter ORDER differs from cosmopower_jax"},
        "accuracy": "matches CAMB to ~0.01% (verified against camb 1.6.6 at Planck point)",
        "citation": "Bonici et al. arXiv:2307.14339",
        "license": "MIT",
        "status": "active",
    },
    # ------------------------------------------------------------ lss family
    "pybird": {
        "family": "lss",
        "role": "EFTofLSS one-loop galaxy power spectrum multipoles (model-independent)",
        "tools": ["compute_galaxy_multipoles"],
        "outputs": "P0/P2/P4(k) [(Mpc/h)^3], k <= kmax (default 0.25 h/Mpc)",
        "ranges": {"note": "takes any linear P(k) as input - no parameter box"},
        "citation": "d'Amico et al.; PyBird arXiv:2003.07956",
        "license": "MIT",
        "status": "active",
    },
    "jax_cosmo": {
        "family": "lss",
        "role": "differentiable Limber Cls (weak lensing / clustering)",
        "tools": ["compute_lensing_cls"],
        "outputs": "dimensionless angular Cl vs multipole",
        "citation": "Campagne et al. arXiv:2302.05163",
        "license": "MIT",
        "status": "active",
    },
    "jaxeffort": {
        "family": "lss",
        "role": "Effort.jl EFTofLSS multipole emulator (JAX port)",
        "tools": [],
        "note": "installed; needs trained model files from the "
                "CosmologicalEmulators zoo - wrap after choosing a release model",
        "citation": "Bonici et al. arXiv:2501.04639",
        "license": "MIT",
        "status": "deferred",
    },
    # -------------------------------------------------------- baryons family
    "pyspk": {
        "family": "baryons",
        "role": "SP(k): baryonic suppression from the fb-Mhalo relation",
        "tools": ["compute_baryon_suppression", "baryonify_pk"],
        "outputs": "P_hydro/P_DMO, k 0.1..12 h/Mpc, z <= 3",
        "ranges": {"fb_normalization": "fb is normalized by Omega_b/Omega_m",
                   "SO": [200, 500]},
        "accuracy": "<= 2% incl. FLAMINGO refits",
        "citation": "Salcido et al. arXiv:2305.09710",
        "license": "LGPL-3.0",
        "status": "active",
    },
    "syren_baryon": {
        "family": "baryons",
        "role": "closed-form baryon suppression fit per hydro suite (CAMELS)",
        "tools": ["compute_baryon_suppression"],
        "outputs": "suppression S(k) per suite: Astrid / IllustrisTNG / SIMBA / Swift-EAGLE",
        "ranges": {"A_SN1": [0.25, 4.0], "A_SN2": [0.5, 2.0],
                   "A_AGN1": [0.25, 4.0], "A_AGN2": [0.5, 2.0]},
        "citation": "Bartlett et al. arXiv:2506.08783",
        "license": "MIT",
        "status": "active",
    },
    "subgrid_emu": {
        "family": "baryons",
        "role": "CRK-HACC subgrid-physics GP emulator with uncertainty (author: N. Ramachandra)",
        "tools": ["emulate_subgrid_statistic"],
        "outputs": "GSMF, CGD, fGas, BHMSM, CSFR, Pk ratio - mean + GP std",
        "ranges": {"kappa_w": [2.0, 4.0], "e_w": [0.2, 1.0],
                   "M_seed_1e6Msun": [0.6, 1.2], "v_kin_1e4kms": [0.1, 1.2],
                   "e_kin_x10": [0.02, 1.2]},
        "citation": "Ramachandra et al. arXiv:2601.07306",
        "license": "not stated in repo (add before public deployment)",
        "status": "active",
    },
    # ---------------------------------------------------------- halos family
    "miratitan_hmf": {
        "family": "halos",
        "role": "Mira-Titan halo mass function GP emulator",
        "tools": ["compute_hmf"],
        "outputs": "dn/dlnM [(Mpc/h)^-3], M200c >= 1e13 Msun/h, z 0..2",
        "ranges": {"Ommh2": [0.12, 0.155], "Ombh2": [0.0215, 0.0235],
                   "Omnuh2": [0.0, 0.01], "sigma_8": [0.7, 0.9],
                   "h": [0.55, 0.85], "n_s": [0.85, 1.05],
                   "w_0": [-1.3, -0.7]},
        "accuracy": "<2% at 1e13-1e14 Msun/h (z<1), <10% at 1e15",
        "citation": "Bocquet et al. arXiv:2003.12116",
        "license": "MIT",
        "status": "active",
    },
    "colossus_hmf": {
        "family": "halos",
        "role": "linear-theory / analytic HMF baselines: Tinker08, Sheth-Tormen, Press-Schechter (colossus)",
        "tools": ["compute_hmf"],
        "outputs": "dn/dlnM [(Mpc/h)^-3] vs M [Msun/h]; tinker08 at 200c/200m/500c, ST+PS at FoF",
        "ranges": {"note": "analytic fits, no training box; any reasonable "
                           "cosmology incl. w0wa. The tool refuses "
                           "mass-definition mismatches (FoF fits vs SO "
                           "masses) that fake factor-of-a-few discrepancies."},
        "accuracy": "tinker08 ~5% vs simulations at its calibrated definitions; PS/ST are historical baselines",
        "citation": "Diemer arXiv:1712.04512 (colossus); Tinker et al. 0803.2706; Sheth & Tormen astro-ph/9901122; Press & Schechter 1974",
        "license": "MIT (colossus)",
        "status": "active",
    },
    "picasso": {
        "family": "halos",
        "role": "cluster gas thermodynamics painted on gravity-only halos (JAX NN)",
        "tools": ["predict_cluster_gas_params"],
        "outputs": "polytropic gas-model parameters per halo",
        "ranges": {"inputs": ["log M200", "c200", "cacc/c200", "cpeak/c200",
                              "log dx/R200c", "e", "p", "a25", "a50", "a75",
                              "almm", "mdot"]},
        "citation": "Keruzore et al. arXiv:2408.17445",
        "license": "MIT",
        "status": "active",
    },
    # ------------------------------------------------------------ igm family
    "lace": {
        "family": "igm",
        "role": "Lyman-alpha forest P1D GP emulator (DESI / igmhub)",
        "tools": ["emulate_lya_p1d"],
        "outputs": "P1D(k_par) in Mpc units, 6-parameter IGM/cosmology compression",
        "ranges": {"Delta2_p": [0.2, 0.6], "n_p": [-2.4, -2.2],
                   "mF": [0.5, 0.9], "sigT_Mpc": [0.09, 0.17],
                   "gamma": [1.0, 1.9], "kF_Mpc": [9.0, 15.0]},
        "citation": "Pedersen et al. arXiv:2011.15127",
        "license": "see repo",
        "note": "installed from repo clone in external/LaCE (pip wheel omits "
                "training data; module-level GPy import patched there)",
        "status": "active",
    },
    "forestflow": {
        "family": "igm",
        "role": "Lyman-alpha P3D(k, mu) normalizing-flow emulator",
        "tools": [],
        "citation": "Chaves-Montero et al.",
        "license": "see repo",
        "status": "deferred",
    },
    "py21cmemu": {
        "family": "igm",
        "role": "21cmFAST summaries emulator (global signal, power spectrum, tau_e)",
        "tools": [],
        "note": "installed; first use downloads ~100s MB weights from HuggingFace",
        "citation": "Breitman et al. arXiv:2309.05697",
        "license": "MIT",
        "status": "deferred",
    },
    "classy_szfast": {
        "family": "cmb",
        "role": "emulator-accelerated CLASS + tSZ/cluster observables",
        "tools": [],
        "note": "installed; first use downloads ~GB of emulator data - "
                "pre-bake at deployment before exposing tools",
        "citation": "Bolliet et al. arXiv:2310.18482",
        "license": "MIT",
        "status": "deferred",
    },
}
